"""Merge the fact-checked per-room captions into the video's events file.

1. Reads the caption workflow's result (JSON: {"batches": [{"captions": [{name, head, why}]}]}), checks every
   segment of the route has exactly one caption and the text fits the panel (head 2x40, why 3x54 characters).
2. Writes zelda/captions.py (CAPTIONS: name -> (head, why)); intent.for_segment consults it first.
3. Rewrites logs/fullgame_run.events.txt: every "head||why" line recorded at a segment's start frame gets that
   segment's caption, and the closing lines are appended.

usage: python apply_captions.py <workflow result json>
"""
import json
import pathlib
import pprint
import sys

import fullgame
import record_run

LOGS = pathlib.Path("logs")
res = json.loads(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8"))
caps = {}
for b in res["batches"]:
    assert b["captions"], f"batch {b['batch']} failed: {b['notes'][:200]}"
    for c in b["captions"]:
        caps[c["name"]] = (c["head"].strip(), c["why"].strip())
names = [s[0] for s in fullgame.segments()]
missing = [n for n in names if n not in caps]
extra = [n for n in caps if n not in names]
assert not missing, f"no caption for {missing[:10]}"
assert not extra, f"captions for unknown segments {extra[:10]}"
long_head = [(n, h) for n, (h, w) in caps.items() if len(h) > 80]
long_why = [(n, len(w)) for n, (h, w) in caps.items() if len(w) > 162]
print(f"{len(caps)} captions; heads over 80 chars: {long_head[:5]}; whys over 162 chars: {long_why[:5]}")

body = pprint.pformat({n: caps[n] for n in names}, width=118, sort_dicts=False)
pathlib.Path("zelda/captions.py").write_text(
    '"""Per-room captions for the video panel: (objective, why) for every segment of the verified sub-hour run.\n\n'
    "Written from each segment's own facts (its policy, the notes above it in fullgame.py, the rooms and supplies\n"
    "before and after, and the enemies the cartridge places in the room), then fact-checked against the same data.\n"
    'Generated by apply_captions.py; intent.for_segment consults this first."""\n\n'
    f"CAPTIONS: dict[str, tuple[str, str]] = {body}\n", encoding="utf-8")
print("wrote zelda/captions.py")

ev_path = LOGS / "fullgame_run.events.txt"
marks = record_run.boundaries("fullgame")
lines = ev_path.read_text(encoding="utf-8").splitlines()
out, replaced, seen = [], 0, set()
for line in lines:
    fr_s, _, txt = line.partition("\t")
    fr = int(fr_s)
    if "||" in txt:
        seg = marks.get(fr - 1) or marks.get(fr)
        if seg is None:
            near = min(marks, key=lambda m: abs(m - fr))
            seg = marks[near] if abs(near - fr) <= 2 else None
        if seg is not None:
            h, w = caps[seg]
            txt = f"{h}||{w}"
            replaced += 1
            seen.add(seg)
    out.append(f"{fr}\t{txt}")
last = max(int(l.split("\t")[0]) for l in out)
total = len(record_run.replay.load_inputs(LOGS / "fullgame.inputs.txt"))
rescue = next(f for f, s in marks.items() if s == "g9_credits")
fmt = lambda f: f"{int(f / 60.0988 // 60)}m{int(f / 60.0988 % 60):02d}s"
out.append(f"{max(last + 400, total - 1600)}\tTHE END||Beaten from power-on: no cheats, no memory writes, no save states "
           f"in the playing. Zelda rescued at {fmt(rescue)} of game time.")
out.append(f"{max(last + 800, total - 400)}\t{total:,} FRAMES - {fmt(total)}||{len(names)} searched segments, "
           f"replayed from power-on and verified (MATCH). The first run took 1h43m.")
ev_path.write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"events: {replaced} caption lines replaced ({len(seen)} segments), closing lines added; rescue {fmt(rescue)}, "
      f"total {fmt(total)}")
