"""Milestone 2: power-on -> new game -> sword -> navigate the overworld to Level 3 -> enter it.

The route was discovered by the explorer (probes/explore_L3.py) using bookmarks. This run uses
no bookmarks at all: every step is planned live from the tile map and executed from power-on.
"""
import time
from zelda import BizHawk, ram, bot, replay, bk2
from zelda.overworld import Navigator, NavError

ROUTE = ["Left", "Up", "Left", "Left", "Left", "Down", "Right"]   # 77 -> 76 -> 66 -> 65 -> 64 -> 63 -> 73 -> 74
L3_ROOM, L3_ENTRANCE_X, L3_ENTRANCE_Y = 0x74, 128, 125             # box fully inside the cave tile at (128,125)

t0 = time.time()
with BizHawk(log_name="milestone2.log", record="milestone2") as emu:
    emu.note("MILESTONE 2: from power-on, get the sword, then walk the discovered route to Level 3")
    bot.new_game(emu)
    bot.enter_cave_up(emu, cave_x=64)
    bot.take_cave_item(emu, item_x=120, flag_addr=ram.SWORD)
    s = bot.exit_cave_down(emu)
    nav = Navigator(emu)
    emu.note(f"Route from exploration: {' -> '.join(ROUTE)}. No bookmarks from here on")
    for d in ROUTE:
        s = nav.exit_screen(d)
        if s.hearts <= 1:
            emu.note(f"WARNING: down to {s.hearts} hearts. Enemies are not handled yet")
    if s.room != L3_ROOM:
        raise SystemExit(f"expected room {L3_ROOM:02X}, got {s}")
    emu.note("On the Level 3 screen. The entrance is the cave tile in the middle: walking under it")
    s = nav.go(lambda x, y: x == L3_ENTRANCE_X and y == L3_ENTRANCE_Y + 16, "the spot below the Level 3 entrance")
    emu.note("Holding UP into the entrance")
    s = emu.wait_until(lambda s: s.level == 3, 300, buttons=("Up",))
    s = emu.wait_until(lambda s: s.mode == ram.MODE_NORMAL, 400)
    emu.note(f"INSIDE LEVEL 3. Room {s.room:02X}, {s.hearts} hearts, frame {s.frame}")
    final = emu.state()
    fp = replay.fingerprint(emu)
    inputs = emu.save_inputs("milestone2")
    emu.save("milestone2_end")
    emu.screenshot("m2_inside_L3")

print(f"run finished in {time.time()-t0:.1f}s wall")
print(f"final state : {final}")
print(f"frames      : {final.frame}  ({final.frame/60.0988:.2f}s of game time)")
print(f"ram sha1    : {fp}")
print("verifying by replay from power-on in a fresh emulator...")
s2, fp2 = replay.verify(inputs, fp)
assert s2.level == 3 and fp2 == fp, "replay mismatch"
movie = bk2.from_inputs_file(inputs, comment="Milestone 2: sword, overworld route, enter Level 3. Generated by the AI harness.")
print(f"bk2 movie   : {movie}")
print("MILESTONE 2 COMPLETE AND VERIFIED")
