"""Milestone 1: from power-on, start a new game, get the sword, walk back out.

Everything is driven by RAM feedback with no savestates, so the resulting input log
replays frame-exactly. The script then replays it in a second emulator to prove that.
"""
import time
from zelda import BizHawk, ram, bot, replay, bk2

t0 = time.time()
with BizHawk(log_name="milestone1.log") as emu:
    bot.new_game(emu)
    s = emu.state()
    assert s.room == ram.START_ROOM, s
    emu.screenshot("m1_start")
    bot.enter_cave_up(emu, cave_x=64)
    emu.screenshot("m1_cave")
    bot.take_cave_item(emu, item_x=120, flag_addr=ram.SWORD)
    emu.wait(30)
    emu.screenshot("m1_sword")
    s = bot.exit_cave_down(emu)
    emu.screenshot("m1_outside")
    final = emu.state()
    fp = replay.fingerprint(emu)
    inputs = emu.save_inputs("milestone1")
    emu.save("milestone1_end")

print(f"run finished in {time.time()-t0:.1f}s wall")
print(f"final state : {final}")
print(f"frames      : {final.frame}  ({final.frame/60.0988:.2f}s of game time)")
print(f"sword       : {final.sword}")
print(f"input log   : {inputs}")
print(f"ram sha1    : {fp}")
print("verifying by replay from power-on in a fresh emulator...")
s2, fp2 = replay.verify(inputs, fp)
assert final.sword == 1 and s2.sword == 1 and fp2 == fp, "replay mismatch"
movie = bk2.from_inputs_file(inputs, comment="Milestone 1: new game, sword cave, back out. Generated by the AI harness.")
print(f"bk2 movie   : {movie}")
print("MILESTONE 1 COMPLETE AND VERIFIED")
